name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
        python-version: ["3.9", "3.10"]
        poetry-version: ["1.0", "1.1.15", "1.2.2"]


    steps:
    - uses: actions/checkout@v3
    
## Clojure dependencies
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@10.1
      with:
       cli: 1.10.1.693              # Clojure CLI based on tools.deps
       lein: 2.9.1                  # Leiningen

## Python dependencies
    - uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: View poetry --help
      run: poetry --help
    
## Emacs dependencies
    - uses: purcell/setup-emacs@master
      with:
        version: 28.2
    - name: "Run tests"  
      run: make test
